/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExtractPriceRouteImport } from './routes/api/extract-price'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedMarketsRouteImport } from './routes/_authenticated/markets'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedListsIndexRouteImport } from './routes/_authenticated/lists.index'
import { Route as AuthenticatedListsIdRouteImport } from './routes/_authenticated/lists.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractPriceRoute = ApiExtractPriceRouteImport.update({
  id: '/api/extract-price',
  path: '/api/extract-price',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketsRoute = AuthenticatedMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListsIndexRoute = AuthenticatedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListsIdRoute = AuthenticatedListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/report': typeof AuthenticatedReportRoute
  '/support': typeof AuthenticatedSupportRoute
  '/api/extract-price': typeof ApiExtractPriceRoute
  '/lists/$id': typeof AuthenticatedListsIdRoute
  '/lists/': typeof AuthenticatedListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/markets': typeof AuthenticatedMarketsRoute
  '/report': typeof AuthenticatedReportRoute
  '/support': typeof AuthenticatedSupportRoute
  '/api/extract-price': typeof ApiExtractPriceRoute
  '/lists/$id': typeof AuthenticatedListsIdRoute
  '/lists': typeof AuthenticatedListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/markets': typeof AuthenticatedMarketsRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/api/extract-price': typeof ApiExtractPriceRoute
  '/_authenticated/lists/$id': typeof AuthenticatedListsIdRoute
  '/_authenticated/lists/': typeof AuthenticatedListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/markets'
    | '/report'
    | '/support'
    | '/api/extract-price'
    | '/lists/$id'
    | '/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/markets'
    | '/report'
    | '/support'
    | '/api/extract-price'
    | '/lists/$id'
    | '/lists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/markets'
    | '/_authenticated/report'
    | '/_authenticated/support'
    | '/api/extract-price'
    | '/_authenticated/lists/$id'
    | '/_authenticated/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiExtractPriceRoute: typeof ApiExtractPriceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-price': {
      id: '/api/extract-price'
      path: '/api/extract-price'
      fullPath: '/api/extract-price'
      preLoaderRoute: typeof ApiExtractPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/markets': {
      id: '/_authenticated/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AuthenticatedMarketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/': {
      id: '/_authenticated/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AuthenticatedListsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists/$id': {
      id: '/_authenticated/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof AuthenticatedListsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMarketsRoute: typeof AuthenticatedMarketsRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedListsIdRoute: typeof AuthenticatedListsIdRoute
  AuthenticatedListsIndexRoute: typeof AuthenticatedListsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMarketsRoute: AuthenticatedMarketsRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedListsIdRoute: AuthenticatedListsIdRoute,
  AuthenticatedListsIndexRoute: AuthenticatedListsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiExtractPriceRoute: ApiExtractPriceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
