
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE public.product_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_key text NOT NULL UNIQUE,
  name text NOT NULL,
  category text NOT NULL,
  unit text NOT NULL DEFAULT 'un',
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.product_catalog TO authenticated, anon;
GRANT ALL ON public.product_catalog TO service_role;

ALTER TABLE public.product_catalog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Catalog readable by everyone"
  ON public.product_catalog FOR SELECT
  USING (true);

CREATE POLICY "Only admins can manage catalog"
  ON public.product_catalog FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE INDEX product_catalog_name_trgm_idx ON public.product_catalog USING gin (lower(name) gin_trgm_ops);
CREATE INDEX product_catalog_category_idx ON public.product_catalog (category);

INSERT INTO public.product_catalog (product_key, name, category, unit) VALUES
('banana-prata', 'Banana prata', 'hortifruti', 'kg'),
('banana-nanica', 'Banana nanica', 'hortifruti', 'kg'),
('maca-gala', 'Maçã gala', 'hortifruti', 'kg'),
('maca-fuji', 'Maçã fuji', 'hortifruti', 'kg'),
('laranja-pera', 'Laranja pera', 'hortifruti', 'kg'),
('laranja-lima', 'Laranja lima', 'hortifruti', 'kg'),
('mamao-papaya', 'Mamão papaya', 'hortifruti', 'kg'),
('mamao-formosa', 'Mamão formosa', 'hortifruti', 'kg'),
('abacaxi', 'Abacaxi', 'hortifruti', 'un'),
('melancia', 'Melancia', 'hortifruti', 'kg'),
('melao', 'Melão', 'hortifruti', 'un'),
('manga-tommy', 'Manga tommy', 'hortifruti', 'kg'),
('manga-palmer', 'Manga palmer', 'hortifruti', 'kg'),
('uva-niagara', 'Uva niágara', 'hortifruti', 'kg'),
('uva-thompson', 'Uva thompson', 'hortifruti', 'kg'),
('pera', 'Pera', 'hortifruti', 'kg'),
('kiwi', 'Kiwi', 'hortifruti', 'kg'),
('morango-bandeja', 'Morango bandeja', 'hortifruti', 'un'),
('abacate', 'Abacate', 'hortifruti', 'kg'),
('limao-tahiti', 'Limão tahiti', 'hortifruti', 'kg'),
('limao-siciliano', 'Limão siciliano', 'hortifruti', 'kg'),
('tangerina', 'Tangerina/mexerica', 'hortifruti', 'kg'),
('coco-seco', 'Coco seco', 'hortifruti', 'un'),
('coco-verde', 'Coco verde', 'hortifruti', 'un'),
('alface-crespa', 'Alface crespa', 'hortifruti', 'un'),
('alface-americana', 'Alface americana', 'hortifruti', 'un'),
('rucula', 'Rúcula', 'hortifruti', 'maço'),
('agriao', 'Agrião', 'hortifruti', 'maço'),
('couve-manteiga', 'Couve manteiga', 'hortifruti', 'maço'),
('espinafre', 'Espinafre', 'hortifruti', 'maço'),
('repolho', 'Repolho', 'hortifruti', 'kg'),
('cenoura', 'Cenoura', 'hortifruti', 'kg'),
('beterraba', 'Beterraba', 'hortifruti', 'kg'),
('batata-inglesa', 'Batata inglesa', 'hortifruti', 'kg'),
('batata-doce', 'Batata doce', 'hortifruti', 'kg'),
('mandioca', 'Mandioca', 'hortifruti', 'kg'),
('inhame', 'Inhame', 'hortifruti', 'kg'),
('cara', 'Cará', 'hortifruti', 'kg'),
('abobora-cabotia', 'Abóbora cabotia', 'hortifruti', 'kg'),
('abobora-paulista', 'Abóbora paulista', 'hortifruti', 'kg'),
('abobrinha', 'Abobrinha', 'hortifruti', 'kg'),
('chuchu', 'Chuchu', 'hortifruti', 'kg'),
('quiabo', 'Quiabo', 'hortifruti', 'kg'),
('berinjela', 'Berinjela', 'hortifruti', 'kg'),
('jilo', 'Jiló', 'hortifruti', 'kg'),
('tomate', 'Tomate', 'hortifruti', 'kg'),
('tomate-italiano', 'Tomate italiano', 'hortifruti', 'kg'),
('cebola', 'Cebola', 'hortifruti', 'kg'),
('cebola-roxa', 'Cebola roxa', 'hortifruti', 'kg'),
('alho', 'Alho', 'hortifruti', 'kg'),
('pimentao-verde', 'Pimentão verde', 'hortifruti', 'kg'),
('pimentao-vermelho', 'Pimentão vermelho', 'hortifruti', 'kg'),
('pimentao-amarelo', 'Pimentão amarelo', 'hortifruti', 'kg'),
('pepino', 'Pepino', 'hortifruti', 'kg'),
('milho-verde-espiga', 'Milho verde (espiga)', 'hortifruti', 'un'),
('vagem', 'Vagem', 'hortifruti', 'kg'),
('ervilha-fresca', 'Ervilha fresca', 'hortifruti', 'kg'),
('brocolis', 'Brócolis', 'hortifruti', 'un'),
('couve-flor', 'Couve-flor', 'hortifruti', 'un'),
('salsinha', 'Salsinha', 'hortifruti', 'maço'),
('cebolinha', 'Cebolinha', 'hortifruti', 'maço'),
('coentro', 'Coentro', 'hortifruti', 'maço'),
('manjericao', 'Manjericão', 'hortifruti', 'maço'),
('gengibre', 'Gengibre', 'hortifruti', 'kg'),
('pimenta-dedo-de-moca', 'Pimenta dedo-de-moça', 'hortifruti', 'kg'),
('file-mignon', 'Filé mignon', 'acougue', 'kg'),
('picanha', 'Picanha', 'acougue', 'kg'),
('alcatra', 'Alcatra', 'acougue', 'kg'),
('contrafile', 'Contrafilé', 'acougue', 'kg'),
('coxao-mole', 'Coxão mole', 'acougue', 'kg'),
('coxao-duro', 'Coxão duro', 'acougue', 'kg'),
('patinho', 'Patinho', 'acougue', 'kg'),
('musculo', 'Músculo', 'acougue', 'kg'),
('acem', 'Acém', 'acougue', 'kg'),
('costela-bovina', 'Costela bovina', 'acougue', 'kg'),
('fraldinha', 'Fraldinha', 'acougue', 'kg'),
('maminha', 'Maminha', 'acougue', 'kg'),
('carne-moida', 'Carne moída', 'acougue', 'kg'),
('carne-moida-patinho', 'Carne moída patinho', 'acougue', 'kg'),
('frango-inteiro', 'Frango inteiro', 'acougue', 'kg'),
('peito-de-frango', 'Peito de frango', 'acougue', 'kg'),
('file-peito-frango', 'Filé de peito de frango', 'acougue', 'kg'),
('coxa-de-frango', 'Coxa de frango', 'acougue', 'kg'),
('sobrecoxa', 'Sobrecoxa', 'acougue', 'kg'),
('coxinha-da-asa', 'Coxinha da asa', 'acougue', 'kg'),
('asa-de-frango', 'Asa de frango', 'acougue', 'kg'),
('coracao-de-frango', 'Coração de frango', 'acougue', 'kg'),
('file-suino', 'Filé suíno', 'acougue', 'kg'),
('lombo-suino', 'Lombo suíno', 'acougue', 'kg'),
('costela-suina', 'Costela suína', 'acougue', 'kg'),
('pernil-suino', 'Pernil suíno', 'acougue', 'kg'),
('bisteca-suina', 'Bisteca suína', 'acougue', 'kg'),
('linguica-toscana', 'Linguiça toscana', 'acougue', 'kg'),
('linguica-calabresa', 'Linguiça calabresa', 'acougue', 'kg'),
('linguica-de-frango', 'Linguiça de frango', 'acougue', 'kg'),
('salsicha', 'Salsicha', 'acougue', 'kg'),
('bacon', 'Bacon', 'acougue', 'kg'),
('presunto', 'Presunto', 'acougue', 'kg'),
('mortadela', 'Mortadela', 'acougue', 'kg'),
('peito-de-peru', 'Peito de peru', 'acougue', 'kg'),
('salame', 'Salame', 'acougue', 'kg'),
('tilapia-file', 'Filé de tilápia', 'peixaria', 'kg'),
('salmao-file', 'Filé de salmão', 'peixaria', 'kg'),
('sardinha-fresca', 'Sardinha fresca', 'peixaria', 'kg'),
('merluza-file', 'Filé de merluza', 'peixaria', 'kg'),
('atum-fresco', 'Atum fresco', 'peixaria', 'kg'),
('camarao-cinza', 'Camarão cinza', 'peixaria', 'kg'),
('camarao-rosa', 'Camarão rosa', 'peixaria', 'kg'),
('bacalhau', 'Bacalhau', 'peixaria', 'kg'),
('pao-frances', 'Pão francês', 'padaria', 'kg'),
('pao-de-forma', 'Pão de forma', 'padaria', 'un'),
('pao-integral', 'Pão integral', 'padaria', 'un'),
('pao-de-queijo', 'Pão de queijo', 'padaria', 'kg'),
('pao-doce', 'Pão doce', 'padaria', 'un'),
('bisnaguinha', 'Bisnaguinha', 'padaria', 'un'),
('croissant', 'Croissant', 'padaria', 'un'),
('bolo-simples', 'Bolo simples', 'padaria', 'un'),
('leite-integral-1l', 'Leite integral 1L', 'laticinios', 'un'),
('leite-desnatado-1l', 'Leite desnatado 1L', 'laticinios', 'un'),
('leite-semi-desnatado-1l', 'Leite semidesnatado 1L', 'laticinios', 'un'),
('leite-zero-lactose-1l', 'Leite zero lactose 1L', 'laticinios', 'un'),
('leite-condensado-395g', 'Leite condensado 395g', 'laticinios', 'un'),
('creme-de-leite-200g', 'Creme de leite 200g', 'laticinios', 'un'),
('iogurte-natural', 'Iogurte natural', 'laticinios', 'un'),
('iogurte-grego', 'Iogurte grego', 'laticinios', 'un'),
('iogurte-frutas', 'Iogurte de frutas', 'laticinios', 'un'),
('queijo-mussarela', 'Queijo mussarela', 'laticinios', 'kg'),
('queijo-prato', 'Queijo prato', 'laticinios', 'kg'),
('queijo-minas-frescal', 'Queijo minas frescal', 'laticinios', 'kg'),
('queijo-minas-padrao', 'Queijo minas padrão', 'laticinios', 'kg'),
('queijo-parmesao', 'Queijo parmesão', 'laticinios', 'kg'),
('queijo-coalho', 'Queijo coalho', 'laticinios', 'kg'),
('requeijao-200g', 'Requeijão cremoso 200g', 'laticinios', 'un'),
('cream-cheese-150g', 'Cream cheese 150g', 'laticinios', 'un'),
('manteiga-200g', 'Manteiga 200g', 'laticinios', 'un'),
('margarina-500g', 'Margarina 500g', 'laticinios', 'un'),
('ovos-duzia', 'Ovos (dúzia)', 'laticinios', 'un'),
('ovos-caipira-duzia', 'Ovos caipira (dúzia)', 'laticinios', 'un'),
('arroz-branco-5kg', 'Arroz branco 5kg', 'mercearia', 'un'),
('arroz-branco-1kg', 'Arroz branco 1kg', 'mercearia', 'un'),
('arroz-integral-1kg', 'Arroz integral 1kg', 'mercearia', 'un'),
('arroz-parboilizado-5kg', 'Arroz parboilizado 5kg', 'mercearia', 'un'),
('feijao-carioca-1kg', 'Feijão carioca 1kg', 'mercearia', 'un'),
('feijao-preto-1kg', 'Feijão preto 1kg', 'mercearia', 'un'),
('feijao-fradinho-500g', 'Feijão fradinho 500g', 'mercearia', 'un'),
('lentilha-500g', 'Lentilha 500g', 'mercearia', 'un'),
('grao-de-bico-500g', 'Grão de bico 500g', 'mercearia', 'un'),
('macarrao-espaguete-500g', 'Macarrão espaguete 500g', 'mercearia', 'un'),
('macarrao-parafuso-500g', 'Macarrão parafuso 500g', 'mercearia', 'un'),
('macarrao-penne-500g', 'Macarrão penne 500g', 'mercearia', 'un'),
('macarrao-instantaneo', 'Macarrão instantâneo', 'mercearia', 'un'),
('macarrao-lasanha-500g', 'Macarrão lasanha 500g', 'mercearia', 'un'),
('farinha-de-trigo-1kg', 'Farinha de trigo 1kg', 'mercearia', 'un'),
('farinha-de-mandioca-500g', 'Farinha de mandioca 500g', 'mercearia', 'un'),
('farinha-de-rosca-500g', 'Farinha de rosca 500g', 'mercearia', 'un'),
('farinha-lactea-400g', 'Farinha láctea 400g', 'mercearia', 'un'),
('fuba-500g', 'Fubá 500g', 'mercearia', 'un'),
('aveia-em-flocos-200g', 'Aveia em flocos 200g', 'mercearia', 'un'),
('granola-1kg', 'Granola 1kg', 'mercearia', 'un'),
('acucar-refinado-1kg', 'Açúcar refinado 1kg', 'mercearia', 'un'),
('acucar-cristal-1kg', 'Açúcar cristal 1kg', 'mercearia', 'un'),
('acucar-demerara-1kg', 'Açúcar demerara 1kg', 'mercearia', 'un'),
('acucar-mascavo-500g', 'Açúcar mascavo 500g', 'mercearia', 'un'),
('adocante-100ml', 'Adoçante 100ml', 'mercearia', 'un'),
('sal-refinado-1kg', 'Sal refinado 1kg', 'mercearia', 'un'),
('sal-grosso-1kg', 'Sal grosso 1kg', 'mercearia', 'un'),
('oleo-de-soja-900ml', 'Óleo de soja 900ml', 'mercearia', 'un'),
('oleo-de-girassol-900ml', 'Óleo de girassol 900ml', 'mercearia', 'un'),
('azeite-extra-virgem-500ml', 'Azeite de oliva extra virgem 500ml', 'mercearia', 'un'),
('azeite-extra-virgem-250ml', 'Azeite de oliva extra virgem 250ml', 'mercearia', 'un'),
('vinagre-de-alcool-750ml', 'Vinagre de álcool 750ml', 'mercearia', 'un'),
('vinagre-de-maca-750ml', 'Vinagre de maçã 750ml', 'mercearia', 'un'),
('molho-de-tomate-340g', 'Molho de tomate 340g', 'mercearia', 'un'),
('extrato-de-tomate-340g', 'Extrato de tomate 340g', 'mercearia', 'un'),
('molho-de-tomate-sache', 'Molho de tomate (sachê)', 'mercearia', 'un'),
('ketchup-380g', 'Ketchup 380g', 'mercearia', 'un'),
('mostarda-200g', 'Mostarda 200g', 'mercearia', 'un'),
('maionese-500g', 'Maionese 500g', 'mercearia', 'un'),
('shoyu-500ml', 'Molho shoyu 500ml', 'mercearia', 'un'),
('molho-ingles-150ml', 'Molho inglês 150ml', 'mercearia', 'un'),
('cafe-em-po-500g', 'Café em pó 500g', 'mercearia', 'un'),
('cafe-em-po-250g', 'Café em pó 250g', 'mercearia', 'un'),
('cafe-em-graos-500g', 'Café em grãos 500g', 'mercearia', 'un'),
('cafe-soluvel-100g', 'Café solúvel 100g', 'mercearia', 'un'),
('capsula-de-cafe', 'Cápsula de café', 'mercearia', 'un'),
('cha-mate-250g', 'Chá mate 250g', 'mercearia', 'un'),
('cha-camomila', 'Chá de camomila', 'mercearia', 'un'),
('cha-preto', 'Chá preto', 'mercearia', 'un'),
('cha-verde', 'Chá verde', 'mercearia', 'un'),
('achocolatado-em-po-400g', 'Achocolatado em pó 400g', 'mercearia', 'un'),
('chocolate-em-po-200g', 'Chocolate em pó 200g', 'mercearia', 'un'),
('leite-em-po-400g', 'Leite em pó 400g', 'mercearia', 'un'),
('biscoito-recheado', 'Biscoito recheado', 'mercearia', 'un'),
('biscoito-agua-e-sal', 'Biscoito água e sal', 'mercearia', 'un'),
('biscoito-cream-cracker', 'Biscoito cream cracker', 'mercearia', 'un'),
('biscoito-maizena', 'Biscoito maizena', 'mercearia', 'un'),
('biscoito-leite', 'Biscoito de leite', 'mercearia', 'un'),
('biscoito-wafer', 'Biscoito wafer', 'mercearia', 'un'),
('torrada-160g', 'Torrada 160g', 'mercearia', 'un'),
('milho-de-pipoca-500g', 'Milho de pipoca 500g', 'mercearia', 'un'),
('pipoca-microondas', 'Pipoca microondas', 'mercearia', 'un'),
('amendoim-200g', 'Amendoim 200g', 'mercearia', 'un'),
('castanha-de-caju-200g', 'Castanha de caju 200g', 'mercearia', 'un'),
('castanha-do-para-200g', 'Castanha-do-pará 200g', 'mercearia', 'un'),
('nozes-200g', 'Nozes 200g', 'mercearia', 'un'),
('uva-passa-200g', 'Uva-passa 200g', 'mercearia', 'un'),
('coco-ralado-100g', 'Coco ralado 100g', 'mercearia', 'un'),
('amido-de-milho-500g', 'Amido de milho 500g', 'mercearia', 'un'),
('fermento-em-po-100g', 'Fermento em pó 100g', 'mercearia', 'un'),
('fermento-biologico-10g', 'Fermento biológico 10g', 'mercearia', 'un'),
('canela-em-po', 'Canela em pó', 'mercearia', 'un'),
('oregano', 'Orégano', 'mercearia', 'un'),
('pimenta-do-reino', 'Pimenta-do-reino', 'mercearia', 'un'),
('coloral-urucum', 'Colorau / urucum', 'mercearia', 'un'),
('cominho', 'Cominho', 'mercearia', 'un'),
('louro', 'Folha de louro', 'mercearia', 'un'),
('caldo-galinha', 'Caldo de galinha', 'mercearia', 'un'),
('caldo-carne', 'Caldo de carne', 'mercearia', 'un'),
('tempero-completo', 'Tempero completo', 'mercearia', 'un'),
('milho-verde-lata', 'Milho verde em lata', 'mercearia', 'un'),
('ervilha-lata', 'Ervilha em lata', 'mercearia', 'un'),
('seleta-de-legumes', 'Seleta de legumes', 'mercearia', 'un'),
('palmito-300g', 'Palmito 300g', 'mercearia', 'un'),
('azeitona-verde', 'Azeitona verde', 'mercearia', 'un'),
('azeitona-preta', 'Azeitona preta', 'mercearia', 'un'),
('atum-em-lata', 'Atum em lata', 'mercearia', 'un'),
('sardinha-em-lata', 'Sardinha em lata', 'mercearia', 'un'),
('mel-300g', 'Mel 300g', 'mercearia', 'un'),
('geleia-de-frutas', 'Geleia de frutas', 'mercearia', 'un'),
('doce-de-leite', 'Doce de leite', 'mercearia', 'un'),
('goiabada', 'Goiabada', 'mercearia', 'un'),
('agua-mineral-1-5l', 'Água mineral 1,5L', 'bebidas', 'un'),
('agua-mineral-500ml', 'Água mineral 500ml', 'bebidas', 'un'),
('agua-com-gas-1-5l', 'Água com gás 1,5L', 'bebidas', 'un'),
('refrigerante-cola-2l', 'Refrigerante cola 2L', 'bebidas', 'un'),
('refrigerante-cola-zero-2l', 'Refrigerante cola zero 2L', 'bebidas', 'un'),
('refrigerante-guarana-2l', 'Refrigerante guaraná 2L', 'bebidas', 'un'),
('refrigerante-laranja-2l', 'Refrigerante laranja 2L', 'bebidas', 'un'),
('refrigerante-uva-2l', 'Refrigerante uva 2L', 'bebidas', 'un'),
('refrigerante-lata-350ml', 'Refrigerante lata 350ml', 'bebidas', 'un'),
('suco-de-uva-integral-1l', 'Suco de uva integral 1L', 'bebidas', 'un'),
('suco-de-laranja-1l', 'Suco de laranja 1L', 'bebidas', 'un'),
('suco-em-po', 'Suco em pó', 'bebidas', 'un'),
('suco-concentrado-500ml', 'Suco concentrado 500ml', 'bebidas', 'un'),
('nectar-200ml', 'Néctar 200ml', 'bebidas', 'un'),
('agua-de-coco-1l', 'Água de coco 1L', 'bebidas', 'un'),
('isotonico-500ml', 'Isotônico 500ml', 'bebidas', 'un'),
('energetico-269ml', 'Energético 269ml', 'bebidas', 'un'),
('cerveja-lata-350ml', 'Cerveja lata 350ml', 'bebidas', 'un'),
('cerveja-long-neck-355ml', 'Cerveja long neck 355ml', 'bebidas', 'un'),
('cerveja-garrafa-600ml', 'Cerveja garrafa 600ml', 'bebidas', 'un'),
('vinho-tinto-750ml', 'Vinho tinto 750ml', 'bebidas', 'un'),
('vinho-branco-750ml', 'Vinho branco 750ml', 'bebidas', 'un'),
('espumante-750ml', 'Espumante 750ml', 'bebidas', 'un'),
('cachaca-700ml', 'Cachaça 700ml', 'bebidas', 'un'),
('vodka-1l', 'Vodka 1L', 'bebidas', 'un'),
('whisky-1l', 'Whisky 1L', 'bebidas', 'un'),
('pizza-congelada', 'Pizza congelada', 'congelados', 'un'),
('lasanha-congelada', 'Lasanha congelada', 'congelados', 'un'),
('nuggets-300g', 'Nuggets 300g', 'congelados', 'un'),
('hamburguer-672g', 'Hambúrguer (caixa)', 'congelados', 'un'),
('batata-palito-congelada-1kg', 'Batata palito congelada 1kg', 'congelados', 'un'),
('legumes-congelados', 'Legumes congelados', 'congelados', 'un'),
('sorvete-2l', 'Sorvete 2L', 'congelados', 'un'),
('acai-1kg', 'Açaí 1kg', 'congelados', 'un'),
('pao-de-queijo-congelado', 'Pão de queijo congelado', 'congelados', 'un'),
('coxinha-congelada', 'Coxinha congelada', 'congelados', 'un'),
('detergente-500ml', 'Detergente líquido 500ml', 'limpeza', 'un'),
('sabao-em-po-1kg', 'Sabão em pó 1kg', 'limpeza', 'un'),
('sabao-em-po-2kg', 'Sabão em pó 2kg', 'limpeza', 'un'),
('sabao-liquido-3l', 'Sabão líquido 3L', 'limpeza', 'un'),
('amaciante-2l', 'Amaciante 2L', 'limpeza', 'un'),
('amaciante-concentrado-500ml', 'Amaciante concentrado 500ml', 'limpeza', 'un'),
('agua-sanitaria-2l', 'Água sanitária 2L', 'limpeza', 'un'),
('alcool-70-1l', 'Álcool 70% 1L', 'limpeza', 'un'),
('alcool-gel-500ml', 'Álcool em gel 500ml', 'limpeza', 'un'),
('desinfetante-2l', 'Desinfetante 2L', 'limpeza', 'un'),
('limpa-vidros-500ml', 'Limpa vidros 500ml', 'limpeza', 'un'),
('multiuso-500ml', 'Multiuso 500ml', 'limpeza', 'un'),
('limpa-banheiro-500ml', 'Limpa banheiro 500ml', 'limpeza', 'un'),
('limpador-perfumado-500ml', 'Limpador perfumado 500ml', 'limpeza', 'un'),
('sabao-em-barra', 'Sabão em barra', 'limpeza', 'un'),
('esponja-de-aco-pacote', 'Esponja de aço (pct)', 'limpeza', 'un'),
('esponja-multiuso', 'Esponja multiuso', 'limpeza', 'un'),
('pano-de-chao', 'Pano de chão', 'limpeza', 'un'),
('pano-multiuso', 'Pano multiuso', 'limpeza', 'un'),
('lustra-moveis-200ml', 'Lustra móveis 200ml', 'limpeza', 'un'),
('inseticida-300ml', 'Inseticida 300ml', 'limpeza', 'un'),
('sacos-de-lixo-30l', 'Sacos de lixo 30L', 'limpeza', 'un'),
('sacos-de-lixo-50l', 'Sacos de lixo 50L', 'limpeza', 'un'),
('sacos-de-lixo-100l', 'Sacos de lixo 100L', 'limpeza', 'un'),
('papel-toalha-2-rolos', 'Papel toalha (2 rolos)', 'limpeza', 'un'),
('guardanapo-pacote', 'Guardanapo (pacote)', 'limpeza', 'un'),
('papel-higienico-12-rolos', 'Papel higiênico 12 rolos', 'higiene', 'un'),
('papel-higienico-4-rolos', 'Papel higiênico 4 rolos', 'higiene', 'un'),
('sabonete-em-barra-90g', 'Sabonete em barra 90g', 'higiene', 'un'),
('sabonete-liquido-250ml', 'Sabonete líquido 250ml', 'higiene', 'un'),
('shampoo-400ml', 'Shampoo 400ml', 'higiene', 'un'),
('condicionador-400ml', 'Condicionador 400ml', 'higiene', 'un'),
('creme-de-pentear', 'Creme de pentear', 'higiene', 'un'),
('creme-dental-90g', 'Creme dental 90g', 'higiene', 'un'),
('enxaguante-bucal-500ml', 'Enxaguante bucal 500ml', 'higiene', 'un'),
('fio-dental', 'Fio dental', 'higiene', 'un'),
('escova-de-dentes', 'Escova de dentes', 'higiene', 'un'),
('desodorante-aerosol-150ml', 'Desodorante aerossol 150ml', 'higiene', 'un'),
('desodorante-roll-on-50ml', 'Desodorante roll-on 50ml', 'higiene', 'un'),
('absorvente-pacote', 'Absorvente (pacote)', 'higiene', 'un'),
('absorvente-interno', 'Absorvente interno', 'higiene', 'un'),
('protetor-diario', 'Protetor diário', 'higiene', 'un'),
('fralda-descartavel-p', 'Fralda descartável P', 'higiene', 'un'),
('fralda-descartavel-m', 'Fralda descartável M', 'higiene', 'un'),
('fralda-descartavel-g', 'Fralda descartável G', 'higiene', 'un'),
('fralda-descartavel-xg', 'Fralda descartável XG', 'higiene', 'un'),
('lenco-umedecido', 'Lenço umedecido', 'higiene', 'un'),
('hidratante-corporal-400ml', 'Hidratante corporal 400ml', 'higiene', 'un'),
('protetor-solar-fps30', 'Protetor solar FPS 30', 'higiene', 'un'),
('barbeador-descartavel', 'Barbeador descartável', 'higiene', 'un'),
('espuma-de-barbear', 'Espuma de barbear', 'higiene', 'un'),
('cotonete', 'Cotonete', 'higiene', 'un'),
('algodao', 'Algodão', 'higiene', 'un'),
('racao-cao-adulto-15kg', 'Ração cão adulto 15kg', 'pet', 'un'),
('racao-cao-filhote-1kg', 'Ração cão filhote 1kg', 'pet', 'un'),
('racao-gato-adulto-1kg', 'Ração gato adulto 1kg', 'pet', 'un'),
('petisco-cao', 'Petisco para cães', 'pet', 'un'),
('areia-higienica-4kg', 'Areia higiênica 4kg', 'pet', 'un'),
('sache-cao', 'Sachê cão', 'pet', 'un'),
('sache-gato', 'Sachê gato', 'pet', 'un'),
('papel-aluminio-30m', 'Papel alumínio 30m', 'outros', 'un'),
('filme-plastico-30m', 'Filme plástico 30m', 'outros', 'un'),
('papel-manteiga', 'Papel manteiga', 'outros', 'un'),
('fosforo', 'Fósforo', 'outros', 'un'),
('isqueiro', 'Isqueiro', 'outros', 'un'),
('vela', 'Vela', 'outros', 'un'),
('pilha-aa', 'Pilha AA', 'outros', 'un'),
('pilha-aaa', 'Pilha AAA', 'outros', 'un'),
('copo-descartavel-200ml', 'Copo descartável 200ml', 'outros', 'un'),
('prato-descartavel', 'Prato descartável', 'outros', 'un'),
('talher-descartavel', 'Talher descartável', 'outros', 'un'),
('canudo', 'Canudo', 'outros', 'un'),
('palito-de-dente', 'Palito de dente', 'outros', 'un');
